language: php
php:
 - nightly

install:
 - composer global require "squizlabs/php_codesniffer=*"

before_script:
 - phpcs --version

script: 
 - phpunit --configuration tests/phpunit.xml 
 - phpcs --standard=PSR2 lib/*

