language: php
php:
 - nightly

install:
 - composer global require "squizlabs/php_codesniffer=*"

script: 
 - phpunit --configuration tests/phpunit.xml 
 - exec vendor/bin/phpcs --standard=PSR2 lib/*

